# Generated by Django 6.0 on 2026-03-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_roles_and_permissions(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    RolePermission = apps.get_model("accounts", "RolePermission")

    matrix = {
        "ADMIN": {
            "description": "Full system administration access.",
            "can_view_records": True,
            "can_create_records": True,
            "can_edit_records": True,
            "can_delete_records": True,
            "can_manage_users": True,
            "can_assign_roles": True,
        },
        "MANAGER": {
            "description": "Operational management with limited user administration.",
            "can_view_records": True,
            "can_create_records": True,
            "can_edit_records": True,
            "can_delete_records": True,
            "can_manage_users": True,
            "can_assign_roles": False,
        },
        "STAFF": {
            "description": "Record operators with CRUD access.",
            "can_view_records": True,
            "can_create_records": True,
            "can_edit_records": True,
            "can_delete_records": True,
            "can_manage_users": False,
            "can_assign_roles": False,
        },
        "VIEWER": {
            "description": "Read-only access to records.",
            "can_view_records": True,
            "can_create_records": False,
            "can_edit_records": False,
            "can_delete_records": False,
            "can_manage_users": False,
            "can_assign_roles": False,
        },
    }

    for name, config in matrix.items():
        role, _ = Role.objects.get_or_create(name=name, defaults={"description": config["description"]})
        RolePermission.objects.update_or_create(
            role=role,
            defaults={
                "can_view_records": config["can_view_records"],
                "can_create_records": config["can_create_records"],
                "can_edit_records": config["can_edit_records"],
                "can_delete_records": config["can_delete_records"],
                "can_manage_users": config["can_manage_users"],
                "can_assign_roles": config["can_assign_roles"],
            },
        )


def rollback_roles_and_permissions(apps, schema_editor):
    RolePermission = apps.get_model("accounts", "RolePermission")
    Role = apps.get_model("accounts", "Role")
    RolePermission.objects.all().delete()
    Role.objects.all().delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=30, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_profiles",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "ordering": ("user__username",),
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("can_view_records", models.BooleanField(default=False)),
                ("can_create_records", models.BooleanField(default=False)),
                ("can_edit_records", models.BooleanField(default=False)),
                ("can_delete_records", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_assign_roles", models.BooleanField(default=False)),
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "ordering": ("role__name",),
            },
        ),
        migrations.RunPython(seed_roles_and_permissions, rollback_roles_and_permissions),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(fields=("role",), name="accounts_rolepermission_unique_role"),
        ),
    ]
