# Generated by Django 6.0 on 2026-02-24 01:26

import apps.core.rbac
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_login', models.BooleanField(default=True)),
                ('allow_anonymous_view', models.BooleanField(default=False)),
                ('allow_anonymous_create', models.BooleanField(default=False)),
                ('allow_anonymous_update', models.BooleanField(default=False)),
                ('allow_anonymous_delete', models.BooleanField(default=False)),
                ('allowed_roles_for_repo_creation', models.JSONField(blank=True, default=list, validators=[apps.core.rbac.validate_role_codes])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users_for_repo_creation', models.ManyToManyField(blank=True, related_name='repo_creation_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
