# Generated by Django 5.2.7 on 2026-02-23 11:31

import apps.records.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AlterModelOptions(
            name='recordattachment',
            options={'verbose_name': 'Record Attachment', 'verbose_name_plural': 'Record Attachments'},
        ),
        migrations.AlterField(
            model_name='record',
            name='case_description',
            field=models.TextField(blank=True, verbose_name='Case Description'),
        ),
        migrations.AlterField(
            model_name='record',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_records', to=settings.AUTH_USER_MODEL, verbose_name='Contributors'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(max_length=100, verbose_name='Record Type'),
        ),
        migrations.AlterField(
            model_name='record',
            name='retention_until',
            field=models.DateField(blank=True, null=True, verbose_name='Retention Until'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='recordattachment',
            name='file',
            field=models.FileField(upload_to=apps.records.storage.record_attachment_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='recordattachment',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='records.record', verbose_name='Record'),
        ),
        migrations.AlterField(
            model_name='recordattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
    ]
