# Generated by Django 6.0 on 2026-02-24 01:25

import apps.core.rbac
import apps.records.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_record_options_alter_recordattachment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='backup/records/pdfs', verbose_name='PDF File'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(default=apps.records.models.now_with_milliseconds, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(default=apps.records.models.now_with_milliseconds, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='Empty means no role restriction.', validators=[apps.core.rbac.validate_role_codes], verbose_name='Allowed Roles')),
                ('created_at', models.DateTimeField(default=apps.records.models.now_with_milliseconds, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=apps.records.models.now_with_milliseconds, verbose_name='Updated At')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_categories', to=settings.AUTH_USER_MODEL, verbose_name='Allowed Users')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.ForeignKey(default=apps.records.models.get_default_category_id, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='records.category', verbose_name='Category'),
        ),
    ]
