# Generated by Django 5.2.7 on 2026-07-13 04:54

import apps.records.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_recordtype_allow_all_contributors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=80, unique=True, verbose_name='Asset Tag')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('server', 'Server'), ('printer', 'Printer'), ('monitor', 'Monitor'), ('projector', 'Projector'), ('scanner', 'Scanner'), ('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('access_point', 'Access Point'), ('ups', 'UPS'), ('nas', 'NAS'), ('tablet', 'Tablet'), ('phone', 'Phone'), ('other', 'Other')], max_length=30, verbose_name='Device Type')),
                ('manufacturer', models.CharField(blank=True, choices=[('dell', 'Dell'), ('hp', 'HP'), ('lenovo', 'Lenovo'), ('acer', 'Acer'), ('asus', 'ASUS'), ('cisco', 'Cisco'), ('mikrotik', 'Mikrotik'), ('apple', 'Apple'), ('canon', 'Canon'), ('epson', 'Epson'), ('brother', 'Brother'), ('other', 'Other')], max_length=30, verbose_name='Manufacturer')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Serial Number')),
                ('operating_system', models.CharField(blank=True, choices=[('windows_11', 'Windows 11'), ('windows_10', 'Windows 10'), ('windows_8_1', 'Windows 8.1'), ('windows_7', 'Windows 7'), ('ubuntu', 'Ubuntu'), ('debian', 'Debian'), ('fedora', 'Fedora'), ('centos', 'CentOS'), ('macos', 'macOS'), ('android', 'Android'), ('ios', 'iOS'), ('none', 'No Operating System')], max_length=30, verbose_name='Operating System')),
                ('system_architecture', models.CharField(blank=True, choices=[('x64', 'x64'), ('x86', 'x86'), ('arm64', 'ARM64')], max_length=10, verbose_name='System Architecture')),
                ('cpu', models.CharField(blank=True, max_length=120, verbose_name='CPU')),
                ('ram', models.CharField(blank=True, max_length=80, verbose_name='RAM')),
                ('storage', models.CharField(blank=True, max_length=120, verbose_name='Storage')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Location')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Department')),
                ('room', models.CharField(blank=True, max_length=80, verbose_name='Room')),
                ('device_owner', models.CharField(blank=True, max_length=150, verbose_name='Device Owner')),
                ('created_at', models.DateTimeField(default=apps.records.models.now_with_milliseconds, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=apps.records.models.now_with_milliseconds, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'IT Asset',
                'verbose_name_plural': 'IT Assets',
                'ordering': ('asset_tag',),
            },
        ),
        migrations.AddField(
            model_name='record',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Technician'),
        ),
        migrations.AddField(
            model_name='record',
            name='assistant_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='Assistant Technician'),
        ),
        migrations.AddField(
            model_name='record',
            name='bios_updated',
            field=models.BooleanField(default=False, verbose_name='BIOS Updated'),
        ),
        migrations.AddField(
            model_name='record',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='Completed By'),
        ),
        migrations.AddField(
            model_name='record',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='record',
            name='date_received',
            field=models.DateField(blank=True, null=True, verbose_name='Date Received'),
        ),
        migrations.AddField(
            model_name='record',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='Diagnosis'),
        ),
        migrations.AddField(
            model_name='record',
            name='drivers_installed',
            field=models.TextField(blank=True, verbose_name='Drivers Installed'),
        ),
        migrations.AddField(
            model_name='record',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Completion Date'),
        ),
        migrations.AddField(
            model_name='record',
            name='final_device_status',
            field=models.CharField(blank=True, choices=[('working', 'Working'), ('working_with_limitations', 'Working with Limitations'), ('beyond_repair', 'Beyond Repair'), ('replaced', 'Replaced'), ('returned_to_user', 'Returned to User'), ('archived', 'Archived')], max_length=40, verbose_name='Final Device Status'),
        ),
        migrations.AddField(
            model_name='record',
            name='firmware_updated',
            field=models.BooleanField(default=False, verbose_name='Firmware Updated'),
        ),
        migrations.AddField(
            model_name='record',
            name='maintenance_status',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('diagnosing', 'Diagnosing'), ('waiting_for_parts', 'Waiting for Parts'), ('repairing', 'Repairing'), ('testing', 'Testing'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=30, verbose_name='Maintenance Status'),
        ),
        migrations.AddField(
            model_name='record',
            name='maintenance_type',
            field=models.CharField(blank=True, choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('installation', 'Installation'), ('upgrade', 'Upgrade'), ('hardware_repair', 'Hardware Repair'), ('software_repair', 'Software Repair'), ('inspection', 'Inspection'), ('network', 'Network')], max_length=30, verbose_name='Maintenance Type'),
        ),
        migrations.AddField(
            model_name='record',
            name='parts_replaced',
            field=models.TextField(blank=True, verbose_name='Parts Replaced'),
        ),
        migrations.AddField(
            model_name='record',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='record',
            name='problem_category',
            field=models.CharField(blank=True, max_length=120, verbose_name='Problem Category'),
        ),
        migrations.AddField(
            model_name='record',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='record',
            name='repair_performed',
            field=models.TextField(blank=True, verbose_name='Repair Performed'),
        ),
        migrations.AddField(
            model_name='record',
            name='reported_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='Reported By'),
        ),
        migrations.AddField(
            model_name='record',
            name='software_installed',
            field=models.TextField(blank=True, verbose_name='Software Installed'),
        ),
        migrations.AddField(
            model_name='record',
            name='support_team',
            field=models.CharField(blank=True, max_length=150, verbose_name='Support Team'),
        ),
        migrations.AddField(
            model_name='record',
            name='testing_results',
            field=models.TextField(blank=True, verbose_name='Testing Results'),
        ),
        migrations.AddField(
            model_name='record',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='records.itasset', verbose_name='IT Asset'),
        ),
    ]
