# Generated by Django 5.2.7 on 2026-07-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_itasset_record_assigned_technician_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itasset',
            name='device_owner',
        ),
        migrations.AddField(
            model_name='itasset',
            name='assigned_user',
            field=models.CharField(blank=True, max_length=150, verbose_name='Assigned User'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='barcode',
            field=models.CharField(blank=True, max_length=120, verbose_name='Barcode / QR Code'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('retired', 'Retired'), ('lost', 'Lost'), ('disposed', 'Disposed'), ('in_storage', 'In Storage')], default='active', max_length=30, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty Expiry'),
        ),
        migrations.AlterField(
            model_name='record',
            name='case_description',
            field=models.TextField(blank=True, verbose_name='Problem Description'),
        ),
        migrations.AlterField(
            model_name='record',
            name='drivers_installed',
            field=models.TextField(blank=True, verbose_name='Driver Updates'),
        ),
        migrations.AlterField(
            model_name='record',
            name='final_device_status',
            field=models.CharField(blank=True, choices=[('working', 'Working'), ('working_with_limitations', 'Working with Limitations'), ('beyond_repair', 'Beyond Repair'), ('replaced', 'Replaced'), ('returned_to_user', 'Returned to User'), ('archived', 'Archived')], max_length=40, verbose_name='Final Outcome'),
        ),
        migrations.AlterField(
            model_name='record',
            name='firmware_updated',
            field=models.BooleanField(default=False, verbose_name='Firmware Updates'),
        ),
    ]
